repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    # -   id: no-commit-to-branch
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: fix-byte-order-marker
        exclude: docs/CNAME
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: mixed-line-ending
        args: [--fix=lf]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args:
        -    --max-line-length=120
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args:
        -    --line-length=120
